import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { copyFileSync, mkdirSync } from "node:fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the plugin source files
*/
`;

const prod = process.argv[2] === "production";

function copyToVaultPlugin() {
	const dest = ".obsidian/plugins/cost-tracker";
	mkdirSync(dest, { recursive: true });
	copyFileSync("main.js", `${dest}/main.js`);
	copyFileSync("manifest.json", `${dest}/manifest.json`);
	copyFileSync("styles.css", `${dest}/styles.css`);
}

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2021",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [
		{
			name: "copy-to-vault-plugin",
			setup(build) {
				build.onEnd((result) => {
					if (result.errors.length === 0) copyToVaultPlugin();
				});
			},
		},
	],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
